### ISSUE TITLE
Hooked part of the page is not translated

### ISSUE THREAD

**Issue by nmpetkov** [craigh/Tag#25]
I started to use this module to make tags available to News module. In news edit page, the section with tags at the end of the page appears not translated (all strings in pot file are translated). It looks like the language module domain is not loaded.

Is this happen to me only, or is a bug?

Module version 1.0.2, Zikula 1.3.6.

![image](https://cloud.githubusercontent.com/assets/628801/6097182/b0e37892-afbb-11e4-87bc-e03576699048.png)

**Comment by craigh** [comment]
it appears the module domain is not set in the templates.

**Comment by nmpetkov** [comment]
I modified file templates/hooks/edit.tpl and added ```domain='module_tag'``` similar to:
        ```<label>{gt text='Add tags' domain='module_tag'}</label>```
but without any effect.

**Comment by nmpetkov** [comment]
So - looking in php code. Similar to what we made in module Newsletter in HookHandlers.php, addnig line:
```
        // Load module, otherwise translation is not working in template
        ModUtil::load('Tag');
```
resolves the problem.

**Comment by craigh** [comment]
nice. can you make a PR?

**Comment by nmpetkov** [comment]
Ok, but in "master" branch? Actually I can't see branch compatible with Zikula 1.3.

**Comment by craigh** [comment]
you're right, there isn't a good place, but still it should be done. If you can add to Master that would be a start, then maybe sometime I can branch a 1.3-compat release and include the stuff that still works with 1.3. Do you know that the master is incompatible with 1.3? I haven't tried it.

**Comment by nmpetkov** [comment]
I downloaded master branch first, and tried to install in Zikula 1.3, but received an error in Admin, Extensions. Then I saw in Version.php (https://github.com/craigh/Tag/blob/master/lib/Tag/Version.php) the limitation to Zikula 1.4, and supposed that master branch is not compatible with Zikula 1.3 anymore, so then downloaded last tagged version of the module.

**Comment by craigh** [comment]
right. It's been a while, so I forget :laughing: 

so yes, let's apply changes to master and then maybe we can figure out how to branch an additional 1.3 compatible release.

**Comment by nmpetkov** [comment]
I've just installed (at least :-)) current dev version build 423 of Zikula, and I'll make tests with News and tag modules, then I'll prepare a PR. The result I'll post here.
