### ISSUE TITLE
Adding multiple tags at once

### ISSUE THREAD

**Issue by nmpetkov** [craigh/Tag#27]
Admin interface to add tags includes possibility to add more then one tag at once:

![image](https://cloud.githubusercontent.com/assets/628801/6200521/4e47e02e-b484-11e4-9c7c-9a10e06373dc.png)

For me it works, after pressing "Add" button, but for first listed tag, entered in the field. Others are ignored.

Even, attempting to add tags one-by-one with 'Add' button, also fails (I have to save the article, then edit it again, to be able to add more tags to the article).

Notice: Already created tags, available to be added by simple click below the field - they can easily be added. This method works. 

Is this happen to me only, or is a bug?

Module version 1.0.3, Zikula 1.3.9.

**Comment by craigh** [comment]
you might check the console log and see if any JS errors are displayed

**Comment by nmpetkov** [comment]
Yeas, it is in conflict in some of my JavaScript loaded, as I checked in new Zikula install, and it works. I'll post here if I find what is the exact reason.

**Comment by nmpetkov** [comment]
Ok, the reason of the conflict was with a JavaScript, loaded by CKEditor, when is configured to use skin "moonocolor". Returning to default "moono" skin resolves the conflict.

So, It is useful to have in mind, but as origin is in CKEditor, I'm closing this ticket.

**Comment by craigh** [comment]
interesting. Maybe the JS in tag could be better encapsulated to prevent future conflicts. I suspect that it will all be converted to jQuery eventually. maybe that will help.

thanks for trouble shooting the problem!

**Comment by nmpetkov** [comment]
And thank you for really useful module! I'd recommend it, and after some usage, I can suggest or help to add some features.

Also, some modules, like News module, can add Tag module as recommended to connect with (for now it recommends Scribite and EZComments only).
Same apply to Pages.

**Comment by craigh** [comment]
you can share your thoughts here: http://zikula.org/library/e/tag#community

I like the module too, but it needs some updating after the core is stable ;-)

**Comment by nmpetkov** [comment]
Thanks for suggestion. I'll start to read docs and use Extension Library :-)
